// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkQKkserE_552sA9zb-RHZ66W-IwXGVFM',
    appId: '1:1086940079074:web:8d05777b6a8f9396cd4fbb',
    messagingSenderId: '1086940079074',
    projectId: 'estrella48-484848',
    authDomain: 'estrella48-484848.firebaseapp.com',
    storageBucket: 'estrella48-484848.appspot.com',
    measurementId: 'G-GN0W265NN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmUnYxryP0_hEK5ExCISy3C44WbGqrPVY',
    appId: '1:1086940079074:android:489a7f9b92453ee1cd4fbb',
    messagingSenderId: '1086940079074',
    projectId: 'estrella48-484848',
    storageBucket: 'estrella48-484848.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMZRLpnHc4zAcBORHxWuvG8QxTc9reaVE',
    appId: '1:1086940079074:ios:24a9b4a19c6b6d3bcd4fbb',
    messagingSenderId: '1086940079074',
    projectId: 'estrella48-484848',
    storageBucket: 'estrella48-484848.appspot.com',
    iosBundleId: 'com.example.estrella48',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMZRLpnHc4zAcBORHxWuvG8QxTc9reaVE',
    appId: '1:1086940079074:ios:24a9b4a19c6b6d3bcd4fbb',
    messagingSenderId: '1086940079074',
    projectId: 'estrella48-484848',
    storageBucket: 'estrella48-484848.appspot.com',
    iosBundleId: 'com.example.estrella48',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkQKkserE_552sA9zb-RHZ66W-IwXGVFM',
    appId: '1:1086940079074:web:2d5d13b554ff11ebcd4fbb',
    messagingSenderId: '1086940079074',
    projectId: 'estrella48-484848',
    authDomain: 'estrella48-484848.firebaseapp.com',
    storageBucket: 'estrella48-484848.appspot.com',
    measurementId: 'G-GGYPNR00QJ',
  );
}
